### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by carloshs1994** [Yothu/Yu-Gi-Oh--Card-Data-Base#32]
# Hi @Yothu 

Great job so far! Your project is looking good so far.

## Highlights:
✅ You have a unique API
✅ Your code looks clean and compact

Keep up the good work!
<img src="https://media4.giphy.com/media/mp1JYId8n0t3y/giphy.gif"/>

**Comment by Yothu** [comment]
Thanks for the review!

**Comment by JohnFTitor** [comment]
# Hi @Yothu and @eduardosancho  👋🏻  

You've done a great job with the project so far. I particularly like the function to load the images, it's really smart. 

## Suggestions

[OPTIONAL] My only suggestion, which may come to personal preference, would be to change or reduce the font-size file approach so it doesn't take space and time to load. 

Keep up the good work 🎉 
Cheers!

<img src="https://media0.giphy.com/media/Js7k1D3Jenq3MUp65Z/giphy.gif"/>

**Comment by Yothu** [comment]
Thanks for the review! I will remove the fonts that are not needed when I finish the project!
